version: "3.8"
services:
  app:
    image: amir20/dozzle
    restart: unless-stopped
    environment:
      - DOZZLE_USERNAME
      - DOZZLE_PASSWORD
      - DOZZLE_NO_ANALYTICS=true
      - DOZZLE_REMOTE_AGENT
      - DOZZLE_AUTH_PROVIDER=simple
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    entrypoint: ["/bin/sh", "-c", "dozzle generate $DOZZLE_USERNAME --password $DOZZLE_PASSWORD > /app/users.yml && /dozzle"]
    networks:
      proxy_apps:

networks:
  proxy_apps:
    name: proxy_apps
    external: true
